name: actions
on:
  workflow_dispatch:
permissions: { }
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
        id: go
      - name: setup cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Build
        run: go build
      - name: Add cache
        uses: actions/cache/save@v3
        with:
          path: ~/work/weather-notification/weather-notification/weather-notification
          key: ${{ runner.os }}-go-${{ github.sha }}
  execute:
    needs: script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache/restore@v3
        with:
          path: ~/work/weather-notification/weather-notification/weather-notification
          key: ${{ runner.os }}-go-${{ github.sha }}
      - name: Execute
        run: ~/work/weather-notification/weather-notification/weather-notification ${{ secrets.CITY_ID }} ${{ secrets.TOKEN_FOR_SLACK_BOT }} ${{ secrets.SLACK_CHANNEL_ID }}
