name: manage_action
on:
  schedule:
    - cron: "13 22 1 * *"
  workflow_dispatch:
permissions:
  actions: write
jobs:
  script:
    uses: tkmsaaaam/manage-slack/.github/workflows/manage_action.yml@main
