name: weather_notification_to_slack
on:
  schedule:
    - cron: "13 20 * * *"
  workflow_dispatch:
permissions: {}
jobs:
  execute:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: ${{ github.workspace }}/${{ github.event.repository.name }}
          key: ${{ runner.os }}-go-${{ github.sha }}
      - name: Execute
        run: ${{ github.workspace }}/${{ github.event.repository.name }}
        env:
          CITY_ID: ${{ secrets.CITY_ID }}
          TOKEN_FOR_SLACK_BOT: ${{ secrets.TOKEN_FOR_SLACK_BOT }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
