name: weather_notification_to_slack
on:
  schedule:
    - cron: '13 20 * * *'
  workflow_dispatch:
permissions: { }
jobs:
  execute:
    needs: script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache/restore@v3
        with:
          path: ~/work/weather-notification/weather-notification/build
          key: ${{ runner.os }}-go-${{ github.sha }}
      - name: Execute
        run: ~/work/weather-notification/weather-notification/build/weather-notification ${{ secrets.CITY_ID }} ${{ secrets.TOKEN_FOR_SLACK_BOT }} ${{ secrets.SLACK_CHANNEL_ID }}
