name: weather_notification_to_slack
on:
  schedule:
    - cron: "13 20 * * *"
  workflow_dispatch:
  workflow_run:
    workflows: [build]
    types: [completed]
permissions: {}
jobs:
  execute:
    uses: tkmsaaaam/count-commits-js/.github/workflows/reusing_execute.yml@main
    secrets:
      CITY_ID: ${{ secrets.CITY_ID }}
      SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
      SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
