name: weather_notification_to_slack
on:
  schedule:
    - cron: '13 20 * * *'
  workflow_dispatch:
permissions: {}
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.19
        id: go
      - name: Run Script
        run: go run main.go  ${{ secrets.CITY_ID }} ${{ secrets.TOKEN_FOR_SLACK_BOT }} ${{ secrets.SLACK_CHANNEL_ID }}
        timeout-minutes: 1
