name: weather_notification_to_slack
on:
  schedule:
    - cron: "13 20 * * *"
  workflow_dispatch:
permissions: {}
jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: ~/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/${{ github.event.repository.name }}
          key: ${{ runner.os }}-go-${{ github.sha }}
      - name: Execute
        run: ~/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/${{ github.event.repository.name }} ${{ secrets.CITY_ID }} ${{ secrets.TOKEN_FOR_SLACK_BOT }} ${{ secrets.SLACK_CHANNEL_ID }}
