name: weather_notification_to_slack
on:
  schedule:
    - cron: '13 20 * * *'
  workflow_dispatch:
permissions: { }
jobs:
  script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19
        id: go
      - name: setup cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - name: Run Script
        run: |
          mkdir build
          go build -o build
      - name: Add cache
        uses: actions/cache@v3
        with:
          path: ~/build
          key: ${{ runner.os }}-go-${{ hashFiles('**.go') }}
          restore-keys: ${{ runner.os }}-go-${{ hashFiles('**.go') }}
      - name: execute
        run: build/weather-notification ${{ secrets.CITY_ID }} ${{ secrets.TOKEN_FOR_SLACK_BOT }} ${{ secrets.SLACK_CHANNEL_ID }}
