name: weather_notification_to_slack
on:
  schedule:
    - cron: "13 20 * * *"
  workflow_dispatch:
  workflow_run:
    workflows: [build]
    types: [completed]
permissions: {}
env:
  CITY_ID: ${{ secrets.CITY_ID }}
  TOKEN_FOR_SLACK_BOT: ${{ secrets.TOKEN_FOR_SLACK_BOT }}
  SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
jobs:
  timeout-minutes: 10
  execute:
    uses: tkmsaaaam/count-commits-js/.github/workflows/reusing.yml@main
