name: weather_notification_to_slack
on:
  schedule:
    - cron: "13 20 * * *"
  workflow_dispatch:
permissions: {}
jobs:
  execute:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: weather-notification
    steps:
      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: ~/work/$REPO_NAME/$REPO_NAME/$REPO_NAME
          key: ${{ runner.os }}-go-${{ github.sha }}
      - name: Execute
        run: ~/work/$REPO_NAME/$REPO_NAME/$REPO_NAME ${{ secrets.CITY_ID }} ${{ secrets.TOKEN_FOR_SLACK_BOT }} ${{ secrets.SLACK_CHANNEL_ID }}
